#ifndef DEFINE_H_
#define DEFINE_H_

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768
#define SCREEN_SIZE CLITERAL(Vector2){SCREEN_WIDTH, SCREEN_HEIGHT}

#define DOG_SOURCE_WIDTH 50
#define DOG_SOURCE_HEIGHT 50
#define DOG_MAX_COUNT 8
#define DOG_SOURCE_RECTANGLE CLITERAL(Rectangle){0,0,DOG_SOURCE_WIDTH,DOG_SOURCE_HEIGHT}

#define DOG_SPRITE_COLUMN 16
#define DOG_SPRITE_ROW 3
#define DOG_SPRITE_ITEM_WIDTH 16
#define DOG_SPRITE_ITEM_HEIGHT 16
#define DOG_SPRITE_WIDTH 256
#define DOG_SPRITE_HEIGHT 48


#define BONE_SOURCE_WIDTH 100
#define BONE_SOURCE_HEIGHT 41
#define BONE_SOURCE_RECTANGLE CLITERAL(Rectangle){0,0,BONE_SOURCE_WIDTH,BONE_SOURCE_HEIGHT}

#define BED_SOURCE_WIDTH 100
#define BED_SOURCE_HEIGHT 100
#define BED_SOURCE_RECTANGLE CLITERAL(Rectangle){0,0,BED_SOURCE_WIDTH,BED_SOURCE_HEIGHT}


#define RUN_SPEED_MIN 100
#define RUN_SPEED_MAX 400
#define TIME_BETWEEN_DOGS 1.0f
#define INITIAL_LIVES 3
#define POINT_PER_DOG 100

#endif